apiVersion: v1
kind: Service
metadata:
  name: wil-playground
spec:
  type: NodePort
  ports:
    - targetPort: 8888
      port: 8888
      nodePort: 8888
  selector:
    app: wil-playground
  ports:
    - protocol: TCP
      port: 8888
